In [7]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
     ------ ------------------------------ 41.0/250.0 kB 653.6 kB/s eta 0:00:01
     ------------------ ------------------- 122.9/250.0 kB 1.2 MB/s eta 0:00:01
     ---------------------------------- --- 225.3/250.0 kB 1.5 MB/s eta 0:00:01
     -------------------------------------- 250.0/250.0 kB 1.4 MB/s eta 0:00:00
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2

In [15]:
glob(dataList)[0]

'C:/data/dataList/happy\\대한민국행복지도_건강.xlsx'

In [72]:
from glob import glob
dataList="C:/data/dataList/happy/*.xlsx"
file=glob(dataList)[0] 
# print(file) # C:/data/dataList/happy\대한민국행복지도_건강.xlsx
# print(file[10:]) # taList/happy\대한민국행복지도_건강.xlsx
print(file.split('_')[1]) # -를 기준으로 대한민국행복지도, 건강 이렇게 스플릿 하고 그 중에서 [1] : 건강.xlsx
print(file.split('_')[1][:-5]) # 대한민국행복지도, 건강 이렇게 스플릿 하고 그 중에서 [1][:-5]을 보겠다 : 건강
print(file.split('_')[1].split('.')[0])  # 윗줄 대신 이거 해도 됨 '건강' 출력  , .split('.')[0]이거 안해주면 '건강.xlsx'출력
import pandas as pd
pd.read_excel(file).head(2)

건강.xlsx
건강
건강

,No,시도,구군,평균,주관적 건강수준 인지율,인구 십만명당 정신건강증진기관 수,인구 천명당 의료기관 종사 의사수,건강생활실천율,인구 천명당 의료기관병상수
0,1,서울특별시,종로구,0.9220,0.8424,0.6914,1.0000,0.9697,0.7616
1,2,서울특별시,중구,0.6742,0.5772,0.4106,0.9995,0.9669,0.4043

In [27]:
from glob import glob
dataList="C:/data/dataList/happy/*.xlsx"
for file in glob(dataList):
    print(file.split('_')[1].split('.')[0]) # - 기준으로 스플릿한 값의 [1] -> [1]을 .을 기준으로 스플릿한 값의 [0]

건강
경제
관계및사회참여
교육
삶의만족도
안전
여가
환경

In [74]:
import pandas as pd
dataList="C:/data/dataList/happy/*.xlsx"
cnt=0

# for로 안하는 이유 문자열이 변수로 들어가야하기 떄문에 안한대...
# for file in glob(dataList):
#     print(file.split('_')[1].split('.')[0])
#     fileName=file.split('_')[1].split('.')[0]
#     fileName=pd.read_excel(file).iloc[:,1:4]
    

file=glob(dataList)[cnt];cnt+=1 #glob함수는 파일이나 디렉토리 경로를 일치하는 패턴으로 검색할 떄 유용 / dataList에 해당하는 파일 경로들을 가져온 후 그 중 cnt인덱스에 해당하는 파일의 경로를 선택하여 file변수에 할당
건강=pd.read_excel(file).iloc[:,1:4] #모든 행, 1부터 3까지의 열  / iloc는 행,열을 선택하는데 사용되는 인덱싱방법
건강

file=glob(dataList)[cnt];cnt+=1
경제=pd.read_excel(file).iloc[:,1:4]

file=glob(dataList)[cnt];cnt+=1
관계및사회참여=pd.read_excel(file).iloc[:,1:4]

file=glob(dataList)[cnt];cnt+=1
교육=pd.read_excel(file).iloc[:,1:4]

file=glob(dataList)[cnt];cnt+=1
삶의만족도=pd.read_excel(file).iloc[:,1:4]

file=glob(dataList)[cnt];cnt+=1
안전=pd.read_excel(file).iloc[:,1:4]

file=glob(dataList)[cnt];cnt+=1
여가=pd.read_excel(file).iloc[:,1:4]

file=glob(dataList)[cnt];cnt+=1
환경=pd.read_excel(file).iloc[:,1:4]

          시도    구군      평균
0      서울특별시   종로구  0.9220
1      서울특별시    중구  0.6742
2      서울특별시   용산구  0.5898
3      서울특별시   성동구  0.4794
4      서울특별시   광진구  0.6373
..       ...   ...     ...
224     경상남도   함양군  0.2036
225     경상남도   거창군  0.2150
226     경상남도   합천군  0.2128
227  제주특별자치도   제주시  0.2537
228  제주특별자치도  서귀포시  0.2537

[229 rows x 3 columns]

In [92]:
건강[(건강['시도']=='서울특별시') & (건강['구군']=='중구')] # 위에서 열 1,2,3만 읽었으므로 시군, 구군, 평균만 나옴 

# 건강[(건강['시도']=='서울특별시') & (건강['평균']>=0.5)]

# 건강[(건강['평균']>0.8) | (건강['평균']<0.3)]
# 건강[(건강['평균']>0.8) | (건강['평균']<0.3)]['시도'] # 평균 0.3넘는 시도만 나옴
# 건강[(건강['평균']>0.8) | (건강['평균']<0.3)]['시도'].unique() # 유니크는 선택된 '시도'열의 고유한 값들 반환

# 건강[(건강['평균']>0.8) | (건강['평균']<0.3)]['시도'] 
# 건강[(건강['평균']>0.8) | (건강['평균']<0.3)]['시도'].value_counts() #최하위 5개보기 
# 건강[(건강['평균']>0.8) | (건강['평균']<0.3)]['시도'].value_counts()[-5:] #최하위 5개보기

      시도  구군      평균
1  서울특별시  중구  0.6742

In [93]:
# 건강[(건강['평균']>0.8) | (건강['평균']<0.3)]['시도']
# 건강[(건강['평균']>0.8) | (건강['평균']<0.3)]['시도'].str.contains('특별')  # 이렇게 하면 안나옴,, 아래처럼 해줘야돼 

# '특별'이 포함된 시도자료중에서 평균값이 0.8보다 크거나 또는 평균값이 0.3보다 작은 시도필드만 보여줘

tmp = 건강[건강['시도'].str.contains('특별')] 
tmp[(tmp['평균']>0.8) | (tmp['평균']<0.3)]  #쓰다맒

          시도    구군      평균
0      서울특별시   종로구  0.9220
12     서울특별시  서대문구  0.8437
74   세종특별자치시   세종시  0.2320
227  제주특별자치도   제주시  0.2537
228  제주특별자치도  서귀포시  0.2537

In [26]:
#시도, 구군 평균이 .. 이거 위아래 장단점 설명해줬어,,, 순서 어쩌구 저쩌구,, 
교육=pd.read_excel(file).iloc[:,1:4] #열의 위치가 바뀌면 코드 수정해야됨, 선택된 열의 의미를 알기 어려울 수 있음
교육=pd.read_excel(file)[['시도','구군','평균']] # 열 위치 바뀌어도 코드 수정할 필요없음, 가독성 좋음 but 열 이름 정확히 알아야함, 보통 코드 수정할 필요없는 이걸 선호함
교육

          시도    구군      평균
0      서울특별시   종로구  0.9220
1      서울특별시    중구  0.6742
2      서울특별시   용산구  0.5898
3      서울특별시   성동구  0.4794
4      서울특별시   광진구  0.6373
..       ...   ...     ...
224     경상남도   함양군  0.2036
225     경상남도   거창군  0.2150
226     경상남도   합천군  0.2128
227  제주특별자치도   제주시  0.2537
228  제주특별자치도  서귀포시  0.2537

[229 rows x 3 columns]

In [94]:
#########################33
###건강자료에서 
###건강_서울특별시.csv로 저장
###건강_부산광역시.csv
###건강_경기.csv로 저장
#######################3###

# 조건 = '서울특별시'
# tmp=건강[건강['시도']==조건]
# # tmp.to_csv('c:/data/dataList/시도별/'+조건+'.csv') # 시도별 폴더에 서울특별시csv생김
# tmp.to_csv('c:/data/dataList/시도별/'+조건+'.csv',index=False, encoding='utf-8') # 이렇게 하면 index사라짐 엑셀 확인해 보기 encoding='utf-8'이건 왜 해준거지 한글깨짐 방지인가 ? 
                                                                                    #맞는것 같아 근데 엑셀파일로 열어보면 여전히 한글깨져나와 

#시도별 csv생김 
조건리스트 = 건강['시도'].unique() # # 유니크는 선택된 '시도'열의 고유한 값들 반환
print(조건리스트)
for 조건 in 조건리스트:
    tmp=건강[건강['시도']==조건]
    tmp.to_csv('c:/data/dataList/시도별/'+조건+'.csv',index=False, encoding='utf-8') # 시도별 폴더에 조건.csv가 생김 
    print(조건, 'save완료')

['서울특별시' '부산광역시' '대구광역시' '인천광역시' '광주광역시' '대전광역시' '울산광역시' '세종특별자치시' '경기도'
 '강원도' '충청북도' '충청남도' '전라북도' '전라남도' '경상북도' '경상남도' '제주특별자치도']
서울특별시 save완료
부산광역시 save완료
대구광역시 save완료
인천광역시 save완료
광주광역시 save완료
대전광역시 save완료
울산광역시 save완료
세종특별자치시 save완료
경기도 save완료
강원도 save완료
충청북도 save완료
충청남도 save완료
전라북도 save완료
전라남도 save완료
경상북도 save완료
경상남도 save완료
제주특별자치도 save완료

In [95]:
건강['시군구']=건강['시도']+'_'+건강['구군'] # colums에 시군구 생기고 그 밑에 '서울특별시_종로구, 서울특별시_중구..'이런식으로 생김 
건강.head()

result=[]
for x in 건강['평균']: # 평균이 0.5 넘으면 상, 아니면 하
    if x>0.5:
        result.append('상')
    else:
        result.append('하')
#for문을 람다로 바꾸라고 GPT에게 물어본거 -> 건강['비고'] = 건강['평균'].apply(lambda x: '상' if x > 0.5 else '하')
#for문은 속도가 떨어지다 보니 간접포인트를 최대한 덜 쓰면서 속도를 높이기 위해 lambda 씀 
건강['비고']=result #결과 값을 비고란에 넣음 
건강.head()

      시도   구군      평균        시군구 비고
0  서울특별시  종로구  0.9220  서울특별시_종로구  상
1  서울특별시   중구  0.6742   서울특별시_중구  상
2  서울특별시  용산구  0.5898  서울특별시_용산구  상
3  서울특별시  성동구  0.4794  서울특별시_성동구  하
4  서울특별시  광진구  0.6373  서울특별시_광진구  상

In [101]:

건강['비고'] = 건강['평균'].apply(lambda x: '상' if x > 0.5 else '하')
건강.head()

      시도   구군      평균        시군구 비고
0  서울특별시  종로구  0.9220  서울특별시_종로구  상
1  서울특별시   중구  0.6742   서울특별시_중구  상
2  서울특별시  용산구  0.5898  서울특별시_용산구  상
3  서울특별시  성동구  0.4794  서울특별시_성동구  하
4  서울특별시  광진구  0.6373  서울특별시_광진구  상

In [100]:
# df=건강.iloc[:,:].copy() #깊은복사를 해야 건강데이터가 변경되었을떄 df데이터가 영향 받지 않음, df=건강 
df=건강.iloc[:,:-2].copy() #열인 시군구, 비고 빠진상태로 복사
# print(df)
#.copy(깊은복사)안하면 원데이터 바뀌면 같이 바뀌게된대
# df.iloc[1,:]
df['비고']=0 #비고란 생성

def aaa(row):
    if row>0.5:
        return '상'
    else :
        return '하'

for cnt,x in enumerate(df['평균']):
    df['비고'][cnt]=aaa(x) #비고란 생성

#람다식의 원리 설명해준거

C:\Users\bluecom010\AppData\Local\Temp\ipykernel_24108\2226055865.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['비고'][cnt]=aaa(x) #비고란 생성
C:\Users\bluecom010\AppData\Local\Temp\ipykernel_24108\2226055865.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '상' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df['비고'][cnt]=aaa(x) #비고란 생성

In [103]:
#강사님의 보내주신 코드 

from glob import glob
import pandas as pd

fileList=glob('c:/data/dataList/happy/*.xlsx')
file=fileList[0]
df=pd.read_excel(file).iloc[:,1:4] #1,2,3열인 시도, 구군, 평균 읽어와 df에 저장
happy=pd.DataFrame({'시도': 
                          df['시도'].unique()}) # df['시도'].unique() : df의 '시도'열에서 고유한 값 추출(중복된 값 제외하고 유일한 값들 가져오는거)
                                                #{'시도': df['시도'].unique()} : 딕셔너리생성 / '시도' : Key,  df['시도'].unique(): Values
                                                #DataFrame <- 판다스에서 제공하는 라이브러리
#print(happy[:3])  #시도데이터를 그룹으로 제작



for file in fileList:
    print(file)
    colName=file.split('_')[1].split('.')[0] #파일명에서 건강, 안전 등 이름 분리
    df=pd.read_excel(file).iloc[:,1:4]
    df.columns=['시도','군구','평균'] # 삶의 만족도.xlsx 파일이 평균필드가 없어서 이름통일
    tmp=df['평균'].groupby(df['시도']).mean()
    happy=pd.merge(happy,tmp.rename(colName), on='시도')

happy.to_csv('c:/data/dataList/happy.csv',index=False, encoding='utf-8')

#메모리 제거하고 다시 자료 불러오는 작업을 권장함
import pandas as pd
df=pd.read_csv('c:/data/dataList/happy.csv')
df

c:/data/dataList/happy\대한민국행복지도_건강.xlsx
c:/data/dataList/happy\대한민국행복지도_경제.xlsx
c:/data/dataList/happy\대한민국행복지도_관계및사회참여.xlsx
c:/data/dataList/happy\대한민국행복지도_교육.xlsx
c:/data/dataList/happy\대한민국행복지도_삶의만족도.xlsx
c:/data/dataList/happy\대한민국행복지도_안전.xlsx
c:/data/dataList/happy\대한민국행복지도_여가.xlsx
c:/data/dataList/happy\대한민국행복지도_환경.xlsx

,시도,건강,경제,관계및사회참여,교육,삶의만족도,안전,여가,환경
0,서울특별시,0.569532,0.532820,0.390656,0.399412,0.490972,0.552256,0.286732,0.470712
1,부산광역시,0.511906,0.438038,0.294719,0.504594,0.362081,0.404875,0.153587,0.448719
2,대구광역시,0.482325,0.393975,0.407486,0.585838,0.363988,0.358429,0.234925,0.552500
3,인천광역시,0.339620,0.410820,0.504920,0.502920,0.411480,0.421020,0.244590,0.515020
4,광주광역시,0.632300,0.387380,0.637800,0.689680,0.484480,0.266440,0.454980,0.607480
5,대전광역시,0.663580,0.416260,0.510820,0.840780,0.407580,0.206780,0.347960,0.582380
6,울산광역시,0.420040,0.642580,0.676440,0.763240,0.471980,0.477060,0.418420,0.393440
7,세종특별자치시,0.232000,0.511900,0.673700,0.587000,0.907700,0.157800,0.447800,0.652400
8,경기도,0.353952,0.468926,0.601532,0.668619,0.426023,0.325255,0.377561,0.557977
9,강원도,0.329506,0.386861,0.563122,0.488533,0.619506,0.548000,0.632750,0.639839
10,충청북도,0.401064,0.484755,0.372782,0.592409,0.410100,0.573155,0.702891,0.466045
11,충청남도,0.347433,0.402893,0.448720,0.648047,0.553100,0.481313,0.625347,0.558173
12,전라북도,0.421300,0.196543,0.487464,0.446936,0.608193,0.410914,0.667900,0.670586
13,전라남도,0.424732,0.202668,0.481323,0.420019,0.547709,0.565195,0.658668,0.700573
14,경상북도,0.264114,0.303355,0.402183,0.428252,0.502223,0.484835,0.490804,0.614265
15,경상남도,0.312722,0.325017,0.395378,0.624022,0.530794,0.475561,0.463750,0.735600
16,제주특별자치도,0.253700,0.425000,0.610700,0.646800,0.711300,0.446100,0.694800,0.684200

In [104]:
# kmeans
#사이킷런은 머신러닝(일반적으로 정형데이터분석)에 특화된 모듈
#하지만 딥러닝에서도 훈련, 테스트 데이터 나누기
#                     결과에 대한 평가 등은 사이킷런 모듈을 사용함
# 사이킷런은 콘다는 scikit-learn, 파이썬은 sklearn
#주의! 사이킷런은 어레이 데이터만 가능
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.3.2-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\bluecom010\miniconda3\envs\openai\lib\site-packages (from scikit-learn) (1.26.2)
Collecting scipy>=1.5.0 (from scikit-learn)
  Downloading scipy-1.11.4-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     -------------------- ------------------- 30.7/60.4 kB 1.4 MB/s eta 0:00:01
     ---------------------------------------- 60.4/60.4 kB 1.6 MB/s eta 0:00:00
Collecting joblib>=1.1.1 (from scikit-learn)
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Downloading threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
Downloading scikit_learn-1.3.2-cp312-cp312-win_amd64.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.1 MB ? eta -:--:--
   - -------------------------------------- 0.4/9.1 MB 3.5 MB/s eta 0:00:03
   --- ------------------------------------ 0.7/9.1 MB 4.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.2/9.1 MB 5.6 MB/s eta 0:00:02
   ------ --------------------------------- 1.5/9.1 MB 6.0 MB/s eta 0:00:02
   ------- -------------------------------- 1.6/9.1 MB 5.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.0/9.1 MB 5.7 MB/s eta 0:00:02
   ---------- ----------------------------- 2.3/9.1 MB 5.9 MB/s eta 0:00:02
   ----------- ---------------------------- 2.6/9.1 MB 6.0 MB/s eta 0:00:02
   ------------- -------------------------- 3.0/9.1 MB 6.2 MB/s eta 0:00:01
   -------------- ------------------------- 3.3/9.1 MB 6.2 MB/s eta 0:00:01
   -------------- ------------------------- 3.4/9.1 MB 6.1 MB/s eta 0:00:01
   ---------------- ----------------------- 3.7/9.1 MB 6.1 MB/s eta 0:00:01
   ------------------ --------------------- 4.2/9.1 MB 6.4 MB/s eta 0:00:01
   -------------------- ------------------- 4.7/9.1 MB 6.6 MB/s eta 0:00:01
   ---------------------- ----------------- 5.1/9.1 MB 6.6 MB/s eta 0:00:01
   ---------------------- ----------------- 5.2/9.1 MB 6.7 MB/s eta 0:00:01
   ----------------------- ---------------- 5.3/9.1 MB 6.2 MB/s eta 0:00:01
   ------------------------ --------------- 5.6/9.1 MB 6.3 MB/s eta 0:00:01
   ------------------------- -------------- 5.9/9.1 MB 6.3 MB/s eta 0:00:01
   -------------------------- ------------- 6.0/9.1 MB 6.0 MB/s eta 0:00:01
   --------------------------- ------------ 6.4/9.1 MB 6.2 MB/s eta 0:00:01
   ----------------------------- ---------- 6.7/9.1 MB 6.3 MB/s eta 0:00:01
   ----------------------------- ---------- 6.8/9.1 MB 6.2 MB/s eta 0:00:01
   ----------------------------- ---------- 6.8/9.1 MB 6.2 MB/s eta 0:00:01
   ------------------------------ --------- 7.0/9.1 MB 5.6 MB/s eta 0:00:01
   ------------------------------- -------- 7.2/9.1 MB 5.7 MB/s eta 0:00:01
   -------------------------------- ------- 7.4/9.1 MB 5.6 MB/s eta 0:00:01
   -------------------------------- ------- 7.4/9.1 MB 5.6 MB/s eta 0:00:01
   -------------------------------- ------- 7.4/9.1 MB 5.6 MB/s eta 0:00:01
   -------------------------------- ------- 7.5/9.1 MB 5.3 MB/s eta 0:00:01
   -------------------------------- ------- 7.5/9.1 MB 5.2 MB/s eta 0:00:01
   --------------------------------- ------ 7.7/9.1 MB 5.0 MB/s eta 0:00:01
   ----------------------------------- ---- 8.1/9.1 MB 5.1 MB/s eta 0:00:01
   ------------------------------------ --- 8.4/9.1 MB 5.1 MB/s eta 0:00:01
   -------------------------------------- - 8.8/9.1 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  9.1/9.1 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 5.2 MB/s eta 0:00:00
Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
   ---------------------------------------- 0.0/302.2 kB ? eta -:--:--
   --------------------------------------  297.0/302.2 kB 17.9 MB/s eta 0:00:01
   ---------------------------------------- 302.2/302.2 kB 9.4 MB/s eta 0:00:00
Downloading scipy-1.11.4-cp312-cp312-win_amd64.whl (43.7 MB)
   ---------------------------------------- 0.0/43.7 MB ? eta -:--:--
   ---------------------------------------- 0.4/43.7 MB 8.1 MB/s eta 0:00:06
    --------------------------------------- 0.9/43.7 MB 10.9 MB/s eta 0:00:04
   - -------------------------------------- 1.4/43.7 MB 9.8 MB/s eta 0:00:05
   - -------------------------------------- 1.7/43.7 MB 9.7 MB/s eta 0:00:05
   - -------------------------------------- 2.1/43.7 MB 9.7 MB/s eta 0:00:05
   -- ------------------------------------- 2.6/43.7 MB 9.6 MB/s eta 0:00:05
   -- ------------------------------------- 3.1/43.7 MB 9.7 MB/s eta 0:00:05
   --- ------------------------------------ 3.4/43.7 MB 9.5 MB/s eta 0:00:05
   --- ------------------------------------ 3.9/43.7 MB 9.5 MB/s eta 0:00:05
   ---- ----------------------------------- 4.4/43.7 MB 9.4 MB/s eta 0:00:05
   ---- ----------------------------------- 4.9/43.7 MB 9.8 MB/s eta 0:00:04
   ---- ----------------------------------- 5.4/43.7 MB 9.9 MB/s eta 0:00:04
   ----- ---------------------------------- 5.7/43.7 MB 9.9 MB/s eta 0:00:04
   ----- ---------------------------------- 5.9/43.7 MB 9.2 MB/s eta 0:00:05
   ----- ---------------------------------- 6.3/43.7 MB 9.1 MB/s eta 0:00:05
   ------ --------------------------------- 6.7/43.7 MB 9.1 MB/s eta 0:00:05
   ------ --------------------------------- 7.0/43.7 MB 9.1 MB/s eta 0:00:05
   ------ --------------------------------- 7.4/43.7 MB 9.1 MB/s eta 0:00:04
   ------- -------------------------------- 7.7/43.7 MB 9.1 MB/s eta 0:00:04
   ------- -------------------------------- 8.0/43.7 MB 9.0 MB/s eta 0:00:04
   ------- -------------------------------- 8.5/43.7 MB 9.0 MB/s eta 0:00:04
   -------- ------------------------------- 8.8/43.7 MB 9.1 MB/s eta 0:00:04
   -------- ------------------------------- 9.3/43.7 MB 9.1 MB/s eta 0:00:04
   -------- ------------------------------- 9.8/43.7 MB 9.2 MB/s eta 0:00:04
   --------- ------------------------------ 10.3/43.7 MB 9.1 MB/s eta 0:00:04
   --------- ------------------------------ 10.7/43.7 MB 9.2 MB/s eta 0:00:04
   ---------- ----------------------------- 11.2/43.7 MB 9.5 MB/s eta 0:00:04
   ---------- ----------------------------- 11.7/43.7 MB 9.2 MB/s eta 0:00:04
   ---------- ----------------------------- 11.9/43.7 MB 9.1 MB/s eta 0:00:04
   ----------- ---------------------------- 12.5/43.7 MB 9.4 MB/s eta 0:00:04
   ----------- ---------------------------- 12.9/43.7 MB 9.4 MB/s eta 0:00:04
   ------------ --------------------------- 13.5/43.7 MB 9.5 MB/s eta 0:00:04
   ------------ --------------------------- 14.0/43.7 MB 9.6 MB/s eta 0:00:04
   ------------- -------------------------- 14.5/43.7 MB 9.6 MB/s eta 0:00:04
   ------------- -------------------------- 14.9/43.7 MB 9.6 MB/s eta 0:00:03
   -------------- ------------------------- 15.4/43.7 MB 9.6 MB/s eta 0:00:03
   -------------- ------------------------- 15.7/43.7 MB 9.5 MB/s eta 0:00:03
   -------------- ------------------------- 16.3/43.7 MB 10.1 MB/s eta 0:00:03
   --------------- ------------------------ 16.8/43.7 MB 10.1 MB/s eta 0:00:03
   --------------- ------------------------ 17.4/43.7 MB 10.4 MB/s eta 0:00:03
   ---------------- ----------------------- 18.0/43.7 MB 10.6 MB/s eta 0:00:03
   ----------------- ---------------------- 18.7/43.7 MB 10.9 MB/s eta 0:00:03
   ----------------- ---------------------- 19.2/43.7 MB 10.9 MB/s eta 0:00:03
   ----------------- ---------------------- 19.6/43.7 MB 10.9 MB/s eta 0:00:03
   ------------------ --------------------- 20.2/43.7 MB 11.1 MB/s eta 0:00:03
   ------------------- -------------------- 20.9/43.7 MB 11.3 MB/s eta 0:00:03
   ------------------- -------------------- 21.5/43.7 MB 11.3 MB/s eta 0:00:02
   -------------------- ------------------- 22.1/43.7 MB 11.7 MB/s eta 0:00:02
   -------------------- ------------------- 22.5/43.7 MB 11.7 MB/s eta 0:00:02
   --------------------- ------------------ 23.1/43.7 MB 11.7 MB/s eta 0:00:02
   --------------------- ------------------ 23.7/43.7 MB 11.7 MB/s eta 0:00:02
   ---------------------- ----------------- 24.3/43.7 MB 11.9 MB/s eta 0:00:02
   ---------------------- ----------------- 25.0/43.7 MB 11.9 MB/s eta 0:00:02
   ----------------------- ---------------- 25.6/43.7 MB 12.1 MB/s eta 0:00:02
   ----------------------- ---------------- 26.2/43.7 MB 12.4 MB/s eta 0:00:02
   ------------------------ --------------- 26.7/43.7 MB 12.4 MB/s eta 0:00:02
   ------------------------- -------------- 27.4/43.7 MB 12.4 MB/s eta 0:00:02
   ------------------------- -------------- 27.9/43.7 MB 12.4 MB/s eta 0:00:02
   -------------------------- ------------- 28.6/43.7 MB 12.6 MB/s eta 0:00:02
   -------------------------- ------------- 29.3/43.7 MB 12.8 MB/s eta 0:00:02
   --------------------------- ------------ 30.1/43.7 MB 13.1 MB/s eta 0:00:02
   ---------------------------- ----------- 30.7/43.7 MB 13.1 MB/s eta 0:00:01
   ---------------------------- ----------- 31.5/43.7 MB 13.4 MB/s eta 0:00:01
   ----------------------------- ---------- 32.2/43.7 MB 13.4 MB/s eta 0:00:01
   ------------------------------ --------- 32.8/43.7 MB 14.2 MB/s eta 0:00:01
   ------------------------------ --------- 33.7/43.7 MB 14.2 MB/s eta 0:00:01
   ------------------------------- -------- 34.1/43.7 MB 14.2 MB/s eta 0:00:01
   ------------------------------- -------- 34.9/43.7 MB 14.2 MB/s eta 0:00:01
   -------------------------------- ------- 35.3/43.7 MB 13.9 MB/s eta 0:00:01
   -------------------------------- ------- 35.7/43.7 MB 13.9 MB/s eta 0:00:01
   --------------------------------- ------ 36.2/43.7 MB 13.6 MB/s eta 0:00:01
   --------------------------------- ------ 36.7/43.7 MB 13.9 MB/s eta 0:00:01
   ---------------------------------- ----- 37.2/43.7 MB 13.6 MB/s eta 0:00:01
   ---------------------------------- ----- 37.7/43.7 MB 13.4 MB/s eta 0:00:01
   ---------------------------------- ----- 38.2/43.7 MB 13.1 MB/s eta 0:00:01
   ----------------------------------- ---- 38.7/43.7 MB 12.8 MB/s eta 0:00:01
   ----------------------------------- ---- 39.1/43.7 MB 12.6 MB/s eta 0:00:01
   ------------------------------------ --- 39.6/43.7 MB 12.4 MB/s eta 0:00:01
   ------------------------------------ --- 40.1/43.7 MB 12.4 MB/s eta 0:00:01
   ------------------------------------- -- 40.7/43.7 MB 12.1 MB/s eta 0:00:01
   ------------------------------------- -- 41.2/43.7 MB 11.9 MB/s eta 0:00:01
   -------------------------------------- - 41.9/43.7 MB 11.9 MB/s eta 0:00:01
   -------------------------------------- - 42.3/43.7 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  42.8/43.7 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------  43.4/43.7 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  43.7/43.7 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------  43.7/43.7 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------- 43.7/43.7 MB 10.2 MB/s eta 0:00:00
Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.3.2 scikit-learn-1.3.2 scipy-1.11.4 threadpoolctl-3.2.0

In [105]:
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

In [118]:
age=np.array([25,30,35,40,45, 50, 55, 60, 65, 70])
purchase_amount=np.array([100, 120, 80, 60, 90, 75, 110, 95, 130, 105])

import pandas as pd
data=pd.DataFrame({'나이':age, '금액':purchase_amount})
data.head()

   나이   금액
0  25  100
1  30  120
2  35   80
3  40   60
4  45   90

In [119]:
data=data.values
data

array([[ 25, 100],
       [ 30, 120],
       [ 35,  80],
       [ 40,  60],
       [ 45,  90],
       [ 50,  75],
       [ 55, 110],
       [ 60,  95],
       [ 65, 130],
       [ 70, 105]])

In [120]:
# k=2
kmeans=KMeans(n_clusters=2)
kmeans.fit(data)

#각 데이터 포인트의 클러스터 할당
labels=kmeans.labels_

#각 클러스터의 중심 좌표
centers=kmeans.cluster_centers_
centers

#시각화
# plt.scatter(, , c=labels, cmap='viridis')
# plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], marker='X', s=200, c='red')
# plt.xlabel('나이')
# plt.ylabel('구매금액')
# plt.title('K-means Clustering')
# plt.legend()
# plt.show()

c:\Users\bluecom010\miniconda3\envs\OpenAI\Lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\bluecom010\miniconda3\envs\OpenAI\Lib\site-packages\sklearn\cluster\_kmeans.py:1440: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

array([[ 39.,  81.],
       [ 56., 112.]])